version: '3.8'

services:
  service1:
    build: ./service1
    container_name: service1
    networks:
      - webnet

  service2:
    build: ./service2
    container_name: service2
    networks:
      - webnet

  nginx:
    build: ./nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - cache_data:/var/cache/nginx
      - /etc/nginx/geoip/GeoLite2-Country.mmdb:/etc/nginx/geoip/GeoLite2-Country.mmdb:ro
    depends_on:
      - service1
      - service2
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  cache_data:
